### ISSUE TITLE
Step does not work in bitrise

### ISSUE THREAD

**Issue by pablosanchezdev** [andrewmarmion/bitrise-step-firebase-dsym-upload#26] opened 2022-11-25 08:57 UTC
The step always fails with bitrise build.
I specify "./AppName/GoogleService-Info.plist" value for the variable Google plist location, but always fails.

**Comment by andrewmarmion** [comment] 2022-11-25 09:29
You really need to provide more information. 

Can you please include any logs from the build process? 

Also please include the following:
- the version of Xcode and macOS that you are building against
- the version of the step that you are using
- the version of FirebaseCrashlytics that you are using 
- that you can confirm you are using the CocoaPod version of FirebaseCrashlytics

Also have you run the bitrise build process locally to ensure that you have everything setup correctly as that is the best way to debug?

**Comment by pablosanchezdev** [comment] 2022-11-25 10:04
This is the message I get from bitrise console

![Captura de pantalla 2022-11-25 a las 11 04 22](https://user-images.githubusercontent.com/15718615/203956986-6eb59eca-e23d-42ad-a900-d4fca6733804.png)

**Comment by andrewmarmion** [comment] 2022-11-25 10:20
The step checks to make sure that you have entered a file path for the location of your GoogleService-Info.plist, it is a very rudimentary check that makes sure the field is not empty. As if it is not a valid file path for the  GoogleService-Info.plist then it will throw an error when it uses Firebase's script. 

As you can see here https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/blob/3dcd109c3740f1747deec13150d09de82ac46d62/step.sh#L16-L20

It will only show this error if you haven't filled something in. 

As the step is working in my projects and my test projects, I really don't have much more information to give you. 

Things to try:
- check the actual YML file to make sure that the variable is set correctly. You can manually edit the YML file to include it. The YML should look like this:
```
    - firebase-dsym-upload@2:
        inputs:
        - fdu_fabric_location: "./Pods/FirebaseCrashlytics/upload-symbols"
        - fdu_google_services_location: "./YOUR-APP-NAME/GoogleService-Info.plist"
```
- ensure that you have saved your workflow after you have edited it. 
- remove the step and re-add it making sure that all of the information is filled in and you have saved the changes in your workflow. 

This is what a successful run of the step should look like (I ran this today from one of my test projects)
<img width="705" alt="CleanShot 2022-11-25 at 10 21 28" src="https://user-images.githubusercontent.com/13627302/203961985-676bba7f-f05d-46fa-93fb-3b43a18717c4.png">

**Comment by pablosanchezdev** [comment] 2022-11-25 10:23
Thanks Andrew for you quick reply!

I have set the variable like this:

![Captura de pantalla 2022-11-25 a las 11 21 46](https://user-images.githubusercontent.com/15718615/203962103-41936b97-f4df-4f1c-a5d7-614d273cd773.png)

I don't know if it's the correct way... where can I find the YML file you say?

**Comment by andrewmarmion** [comment] 2022-11-25 10:35
The YML can be found in the Workflow Editor on Bitrise 

<img width="1227" alt="CleanShot 2022-11-25 at 10 35 18" src="https://user-images.githubusercontent.com/13627302/203964698-eb503952-a91b-404a-8abb-c7a9e65d91da.png">

**Comment by andrewmarmion** [comment] 2022-11-25 10:36
> Thanks Andrew for you quick reply!
> 
> I have set the variable like this:
> 
> ![Captura de pantalla 2022-11-25 a las 11 21 46](https://user-images.githubusercontent.com/15718615/203962103-41936b97-f4df-4f1c-a5d7-614d273cd773.png)

That looks correct.

**Comment by andrewmarmion** [comment] 2022-11-25 10:36
> I don't know if it's the correct way... where can I find the YML file you say?

The YML can be found in the Workflow Editor on Bitrise 

<img width="1227" alt="CleanShot 2022-11-25 at 10 35 18" src="https://user-images.githubusercontent.com/13627302/203964698-eb503952-a91b-404a-8abb-c7a9e65d91da.png">

**Comment by pablosanchezdev** [comment] 2022-11-25 11:04
Both the variable and YML files are correct, and it keeps failing :(

**Comment by andrewmarmion** [comment] 2022-11-25 11:20
If you have tried all the suggestions that I have made and it is still failing, I really don't have an answer for you. 

I am unable to reproduce the error myself.

**Comment by andrewmarmion** [comment] 2022-12-21 17:47
Closing this as I am unable to reproduce and there has been no further updates.

**Closed as completed by andrewmarmion** 2022-12-21 17:47 UTC
Labels: unable to reproduce
