### ISSUE TITLE
Upload dsym error without more information

### ISSUE THREAD

**Issue by davilinho** [andrewmarmion/bitrise-step-firebase-dsym-upload#22] opened 2022-07-26 07:41 UTC
Hello, 

I've this error when upload throught Bitrise, so I don't found more information about it

`+------------------------------------------------------------------------------+

| (10) firebase-dsym-upload@2                                                  |
+------------------------------------------------------------------------------+
| id: firebase-dsym-upload                                                     |
| version: 2.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-07-26T07:23:40Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Fabric is being deprecated November 15 2020.
Make sure you update your dependencies to use FirebaseCrashlytics before then.
/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise265402707/step_src/step.sh: line 34: 13466 Segmentation fault: 11  "$fdu_fabric_location" -gsp "$fdu_google_services_location" -p ios "$fdu_dsym_location"
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | firebase-dsym-upload@2 (exit code: 139)                       | 39.58 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/andrewmarmion/bitrise-step-firebase-dsym-upload/issues |
| Source: https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload   |
+---+---------------------------------------------------------------+----------+`

Where is the problem?

**Comment by andrewmarmion** [comment] 2022-07-26 10:34
I don't know where the issue is. 

Are you use CocoaPods or SPM? 
Have you filled in all values correctly in the step for location of the FirebaseCrashlytics CocoaPod, the GoogleService-Info.plist and the dSYM? 
Which version of the FirebaseCrashlytics CocoaPod are you using?

For your information this script is just a wrapper around the upload script that is contained within the FirebaseCrashlytics CocoaPod.

**Comment by andrewmarmion** [comment] 2022-08-02 08:14
Closing this as there have been no updates

**Closed as not planned** 2022-08-02 08:14 UTC
